env:
  global:
  - secure: dR5frTHHcDebRs4wQh9ZEpHmF7AafgpkZP7/tp5f/zRbkRLfnZT75PIMLZ4HsYFA9nU0VRos5LZvnd2E5dZRPPhtXZwd4h9apvb9n15ADwQtJ/3eyK+nvJNfGGQkuPAFC5KPFXYCcClHcnbagRve9sH/+6PPV3iOKxQiHIUZN5ASoeGASwRvv/MDgTkRUwKLLZngjK0htac0UBZa4UDcegBTAcMTv+vmjii9gRi7HE25NtCb1Bzgetn4RVgeqj/fe7b1wzWNADXE4Zwd5TyDTL3WwW4R1QmPf4FxMc30UixLU5xUS9jYxMxAdZktF13Ra5cKNPNBIIwOwFpSd30WC9tOGZrhqUdHtzCsW6PMyg2EJf0cBog/TzC96I3dyDIjdUTzkjQ5bg92xN63VhVuEpcOj8E2f8aRA/zy+AqXu0hunOe8LyzkUwLa5PrPsMyTrP6Eh3gfxbU3Thi/q1LAxk9tELEIwq02wapRCWmOmRHr8EK2OrWjKCO2pMpIdBonhofeNFL01jyvVlHomvuOcyQxN6Xx4/0Xa8NTO0tF4HMg1XsnOl1+nuGZW82Fm9RLcaN7ScBfZN/zH79bQR4COOLoaTnzGW4S9EYEV9DOiWu8TyK8akrKE7Ztov0QLt5rwScDo6I/d0BOaLysNOfHUF/CGMjLZdHm/+WdIuGrqx8=
language: go
go:
- '1.14'
- '1.15'
addons:
  sonarcloud:
    organization: aphistic
    token:
      secure: iK1b0g5ZIwDZKaANCtxao+8Oa+zpNt+wulnuvIhHByAbjvdQ/WafkKDtCyusC3qApMC7CCdn7ejUA8xMuia08o7GCt09HuwuXeGRNgwPfWKKUXSa2c9hqIa8qH2Rg2hmlcY0cAAc2etD1e3OkDhrLwleJOr9/3RIGeD61rQcCjBU+EyaiffxS/LJ/aN8C+VcyoE/+IcNOJacwb/AUDfk20X8VFXZ+9nwTQQAR+DnkLDM910lC91kka+NBOxRkxq0YmAhNmtfTGPlVukkYg5lQKIBOww2h0YaXQRGmjj7eSX4ry1Uk/6aea486BBuMm3Nw4yfKxahVf+4BRlggQmU+0wLoDmzqDaIWnFrTuQiFarRrr7D0zLs/kW9v7aHP5R93xFbtES4/YGRio4Vu40yBj+LF9nieg+XyEjsIbXRW8IFCWRDgBlAfx+QWKRhGVKcMlnq0ZWhpsbpRJ+7R/W2/W1gRGqDdjqSX3Zv8o5FzPU4P3m/qpMCpBNXWteP9HPqY5je4/dJCkj6PfdbhkYfdCVJDWo1BT6blQlRI5uBWFUFYgPI/y3sSAMRHuC/NbQf9qsc8y5EgfUqZk6yfLapHTXg3YzVoGUTvDaE+ajv9oCQqoSw5zyknFRIE46u3aUWHVvfRnBZ2QY3ztIOeFdaQo6Jrv8w7AzVmDmlMVTZjT4=
script:
- sonar-scanner
